### PR TITLE
docs: home, about

### PR DESCRIPTION
**Pull request by cybanjar**

### CODE REVIEW

**Review by syamsulamin — APPROVED** [review]

**Review by syamsulamin — APPROVED** [review]
nice

**Review by cybanjar — COMMENTED** [review]
ok

**Review by syamsulamin — CHANGES_REQUESTED** [review]
weh

**Review by syamsulamin — APPROVED** [review]

**Review by syamsulamin — APPROVED** [review]
mantap

**Review by syamsulamin — CHANGES_REQUESTED** [review]
nice

**Review by syamsulamin — APPROVED** [review]
ok

**Pull request merged**
